### ISSUE TITLE
Update React APP with redux , thunk (Actions contain middleware) , services and Axios base communication

### ISSUE THREAD

**Issue by prasad21jan** [karpolan/react-typescript-material-ui-with-auth-starter#11]
Please update React APP with redux , thunk (Actions contain middleware) , services and Axios base communication

**Comment by karpolan** [comment]
Good point, but not every application uses Redux or even Axios.

Maybe it is good idea to create another template for Redux. If you want we can create it together.

**Comment by karpolan** [comment]
No plans for Redux
